"use client";

import { useState } from "react";
import Image from "next/image";
import { Container, Reveal } from "@/components/ui";

const MODELS = [
  {
    dir: "Inbound",
    dirBg: "bg-sky-700/10 text-sky-700",
    dirIcon: "←",
    title: "Reference / directory connection",
    status: "Available",
    statusBg: "bg-green-700/10 text-green-700",
    statusDot: "bg-green-700",
    desc: "Read approved reference data from another authoritative system.",
    tags: ["Organization reference", "Location data", "Identity directory"],
    writeAuth: "Read-only",
    note: "Zoiko HR must not imply ownership of external authoritative truth.",
  },
  {
    dir: "Inbound",
    dirBg: "bg-sky-700/10 text-sky-700",
    dirIcon: "←",
    title: "Inbound operational feed",
    status: "Available",
    statusBg: "bg-green-700/10 text-green-700",
    statusDot: "bg-green-700",
    desc: "Receive operational records generated by external systems into designated staging or ledger areas.",
    tags: ["Timesheet feeds", "Expense entries", "Attendance logs"],
    writeAuth: "Staging write",
    note: "Incoming data must pass pre-flight validation before committing to records.",
  },
  {
    dir: "Outbound",
    dirBg: "bg-green-700/10 text-green-700",
    dirIcon: "→",
    title: "Outbound operational feed",
    status: "Contact to confirm",
    statusBg: "bg-gray-500/10 text-gray-500",
    statusDot: "bg-gray-500",
    desc: "Export approved employee status changes and payroll preparation data to external receivers.",
    tags: ["Payroll preparation", "Benefits enrollment", "Directory sync"],
    writeAuth: "Export stream",
    note: "Requires explicit column selection and customer-managed delivery targets.",
  },
  {
    dir: "Bidirectional",
    dirBg: "bg-violet-600/10 text-violet-600",
    dirIcon: "↔",
    title: "Bidirectional synchronization",
    status: "Contact to confirm",
    statusBg: "bg-gray-500/10 text-gray-500",
    statusDot: "bg-gray-500",
    desc: "Two-way record alignment with strict conflict resolution rules and source-of-truth field boundaries.",
    tags: ["HR master sync", "SCIM user provisioning"],
    writeAuth: "Field-level permission",
    note: "Each field is explicitly mapped to a single authoritative source.",
  },
  {
    dir: "Event",
    dirBg: "bg-amber-700/10 text-amber-700",
    dirIcon: "⚡",
    title: "Event / notification integration",
    status: "Available",
    statusBg: "bg-green-700/10 text-green-700",
    statusDot: "bg-green-700",
    desc: "Subscribe to real-time webhooks or dispatch external notifications upon key lifecycle events.",
    tags: ["New hire triggers", "Termination alerts", "Approval webhooks"],
    writeAuth: "Event trigger",
    note: "Payloads contain minimal necessary identifiers with encrypted webhook signatures.",
  },
  {
    dir: "Identity",
    dirBg: "bg-blue-600/10 text-blue-600",
    dirIcon: "⊙",
    title: "Identity / access federation",
    status: "Available",
    statusBg: "bg-green-700/10 text-green-700",
    statusDot: "bg-green-700",
    desc: "Federate single sign-on authentication and automated user provisioning via standard SAML 2.0 or OIDC.",
    tags: ["SAML 2.0 SSO", "OIDC Connect", "OAuth2 delegation"],
    writeAuth: "Federated auth",
    note: "Governed by Identity & Single Sign-On module authority.",
  },
  {
    dir: "Batch",
    dirBg: "bg-gray-500/10 text-gray-500",
    dirIcon: "⊞",
    title: "One-time / batch movement",
    status: "Available",
    statusBg: "bg-green-700/10 text-green-700",
    statusDot: "bg-green-700",
    desc: "Execute bulk data import or export jobs for legacy migrations or periodic compliance archives.",
    tags: ["CSV/XLSX imports", "Historical archives", "SFTP bulk export"],
    writeAuth: "Batch job permission",
    note: "Governed by Data Import & Export module rules.",
  },
];

export function ConnectionModelDirectorySection() {
  const [expandedIdx, setExpandedIdx] = useState<number | null>(0);

  return (
    <section className="bg-slate-50 py-16 lg:py-24 border-t border-slate-200" id="connection-models">
      <Container>
        <div className="space-y-12 max-w-6xl mx-auto">
          <div className="grid lg:grid-cols-12 gap-12 items-start">
            <div className="lg:col-span-4 space-y-6">
              <Reveal>
                <span className="text-blue-600 text-xs font-medium font-['IBM_Plex_Sans'] uppercase leading-4 tracking-wider">
                  Connection Model Directory
                </span>
              </Reveal>

              <Reveal delay={0.08}>
                <h2 className="text-3xl font-extrabold text-slate-950 font-['Manrope'] leading-10 max-w-[288px]">
                  Seven catalog-backed connection model classes
                </h2>
              </Reveal>

              <Reveal delay={0.12}>
                <p className="text-slate-600 text-sm font-normal font-['IBM_Plex_Sans'] leading-6 max-w-[288px]">
                  Model classes are a design contract for classification — not a promise that every type is supported for every organization, market or plan. Specific availability comes from the approved Integration Catalog.
                </p>
              </Reveal>

              <Reveal delay={0.16}>
                <div className="relative rounded-xl outline outline-1 outline-offset-[-1.01px] outline-amber-200 bg-amber-50 overflow-hidden shadow-sm">
                  <Image
                    src="/images/integration-overview/image 434.png"
                    alt="Connection Model Classes Directory"
                    width={355}
                    height={355}
                    className="w-full h-auto object-cover rounded-xl"
                  />
                </div>
              </Reveal>
            </div>

            <div className="lg:col-span-8 space-y-2">
              {MODELS.map((item, idx) => {
                const isExpanded = expandedIdx === idx;
                return (
                  <Reveal key={idx} delay={0.04 * idx + 0.1}>
                    <div className="bg-white rounded-xl outline outline-1 outline-offset-[-1.01px] outline-slate-200 overflow-hidden transition-all">
                      <button
                        onClick={() => setExpandedIdx(isExpanded ? null : idx)}
                        className="w-full px-5 py-4 text-left flex items-center justify-between gap-4 focus:outline-none"
                      >
                        <div className="flex items-center gap-3">
                          <span className={`px-2 py-0.5 rounded-sm text-xs font-medium font-['IBM_Plex_Sans'] leading-4 flex items-center gap-1 ${item.dirBg}`}>
                            <span>{item.dirIcon}</span>
                            <span>{item.dir}</span>
                          </span>
                          <span className="text-slate-950 text-xs font-semibold font-['IBM_Plex_Sans'] leading-5">
                            {item.title}
                          </span>
                        </div>

                        <div className="flex items-center gap-3">
                          <span className={`px-2.5 py-1 rounded-full text-xs font-medium font-['IBM_Plex_Sans'] leading-4 flex items-center gap-1.5 ${item.statusBg}`}>
                            <span className={`w-1.5 h-1.5 rounded-full ${item.statusDot}`} />
                            {item.status}
                          </span>
                          <span className="text-slate-400 font-normal text-xs">
                            {isExpanded ? "▲" : "▼"}
                          </span>
                        </div>
                      </button>

                      {isExpanded && (
                        <div className="px-5 pb-5 pt-4 border-t border-slate-100 space-y-3 text-xs font-['IBM_Plex_Sans']">
                          <p className="text-slate-600 font-normal font-['IBM_Plex_Sans'] leading-5">
                            {item.desc}
                          </p>

                          <div className="flex flex-wrap items-center gap-1.5 pt-1">
                            {item.tags.map((t, tIdx) => (
                              <span key={tIdx} className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded-sm text-xs font-normal font-['JetBrains_Mono'] leading-4">
                                {t}
                              </span>
                            ))}
                          </div>

                          <div className="pt-2">
                            <span className="text-gray-400 text-xs font-medium font-['IBM_Plex_Sans'] leading-4">Write authority: </span>
                            <span className="text-slate-950 text-xs font-normal font-['JetBrains_Mono'] leading-4">{item.writeAuth}</span>
                          </div>

                          <div className="p-3 bg-slate-50 rounded-sm outline outline-1 outline-offset-[-1.01px] outline-slate-200 text-gray-500 text-xs font-medium font-['IBM_Plex_Sans'] leading-4 flex items-start gap-2">
                            <span>→</span>
                            <span>{item.note}</span>
                          </div>
                        </div>
                      )}
                    </div>
                  </Reveal>
                );
              })}
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
}

